language: node_js
node_js: lts/*
before_script:
- npm install -g electron-builder
script: npm run dist
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
deploy:
  provider: releases
  draft: true
  api_key:
    secure: kW2IFffTqU0sI0besDqLwHV5B9De6dknn0bhR7wiY2h7ntoalIVMhNhQKfOmJyZY60WYGSkyFAnUfRUu0dEe8CoCPsm4vuvDvAgQnoh0u1GqUnQ/YDYIX7xXJjOIU4tc8B3SGxMTJbgJhOCEVe4bl8oy2snIMtNQ4k9T0fAZQcILEhEOzAEsgU8at03RGcK4KD650YozG3RUgRPXhC1rQkKaznp2/OIoorIvsKi9EdqRkCmNygHrPBYxygzlDeGCpyPSYUQUHFj4D001tFcq/HJfp0swZ/IxjPChorwK3fw2gyBDEJgYaw/2070iB4+WH7YMl5dUaTjAM3KIt3sx6QRwyDD7bvqFhrEe+GuvNXMNmZmxEY7u7YZM2T21hncuPAvSZ6Md38Kht/ErvX43cqnmng0hsBvEnNj6JCsRKUwj47/E92aE7/Os+ivqHAGrEXZpaX3bkkkzuDbV408qD2u5kQQLAY6GS1p/qyfmyoaUTIfYZNYJCbtuxlEjKfMyF6cBzVmEuYx6vnkteZxpxmA5YB9vuFnf1NUIhCY7IuCSiA/F/9TkllTD/teZwvDtatAhesHXYTwgn7Q6Q6rVcgmkN9N/i+1r0a57HILMdzO3xb7VRddh8Vr88i0F5GArzJlDY5wqRhz4M91kHPM2TVPRVFlG3YFYWkfcFCQAteg=
  file_glob: true
  file:
    - dist/phonepresenter*
    - dist/PhonePresenter*.exe
    - dist/PhonePresenter*.dmg
  skip_cleanup: true
  on:
    repo: PhonePresenter/PhonePresenter
    tags: true
    branch: release
